
package com.vignette.idm.render.manager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
public interface RenderManagerServiceSoap {


    /**
     * 
     * @param resultMsg
     * @param rendererType
     * @param serverID
     * @param agentType
     * @param rendRef
     * @param rendererProgID
     * @return
     *     returns int
     */
    public int getRendererRef(
       
        String rendererType,
        
        String agentType,
        
        String serverID,
        
        String rendRef,
       
        String rendererProgID,
        
        String resultMsg);

    /**
     * 
     * @param resultMsg
     * @param rendererType
     * @param serverID
     * @return
     *     returns int
     */
    public int releaseRendererRef(
        
        String rendererType,
       
        String serverID,
        
        String resultMsg);

    /**
     * 
     * @param resultMsg
     * @param ppList
     * @return
     *     returns int
     */
    public int getRendererList(
        
        com.vignette.idm.render.manager.GetRendererListResponse.PpList ppList,
       
        String resultMsg);

    /**
     * 
     * @param resultMsg
     * @param pbstrDescription
     * @param bstrType
     * @param pbstrConfigURI
     * @return
     *     returns int
     */
    public int getRendererInfo(
       
        String bstrType,
       
        String pbstrDescription,
        
        String pbstrConfigURI,
        
        String resultMsg);

}
