
package com.vignette.idm.render.agent;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
public class RenderAgentSoapService
    extends Service
{

    private final static URL RENDERAGENTSOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.vignette.idm.render.agent.RenderAgentSoapService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.vignette.idm.render.agent.RenderAgentSoapService.class.getResource(".");
            url = new URL(baseUrl, "file:/vobs/source/prod/TDP.NET/WebServices/RenderingServices/RenderClient/WebReferences/Agent/RenderAgentSoap.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/vobs/source/prod/TDP.NET/WebServices/RenderingServices/RenderClient/WebReferences/Agent/RenderAgentSoap.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RENDERAGENTSOAPSERVICE_WSDL_LOCATION = url;
    }

    public RenderAgentSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RenderAgentSoapService() {
        super(RENDERAGENTSOAPSERVICE_WSDL_LOCATION, new QName("urn:RenderAgentSoapService", "RenderAgentSoapService"));
    }

    /**
     * 
     * @return
     *     returns RenderAgentSoapServiceSoap
     */
 
    public RenderAgentSoapServiceSoap getRenderAgentSoapServiceSoap() {
        return super.getPort(new QName("urn:RenderAgentSoapService", "RenderAgentSoapServiceSoap"), RenderAgentSoapServiceSoap.class);
    }

}
